const express = require('express')
const { test } = require('../controllers/test')
const { registerUser } = require('../controllers/register')
const { regitrationVerification } = require('../controllers/verifyRegisteration.js')
const { login } = require('../controllers/login.js')
const { protectedRoute } = require('../middlewware/verifyTokenMiddleware.js')
const { protectedRouteHandler } = require('../controllers/ptotectedRoute.js')
const router = express.Router()
router.use(express.json())

router.get('/test', test)
router.get('/verify', regitrationVerification)
router.post('/register', registerUser)
router.post('/login', login)
router.get('/protected', protectedRoute, protectedRouteHandler)
module.exports = router