const { query } = require("../../config/db");
const { errorGenerator } = require("../../utils/errorGenarator");

const fetchAdminAnalytics = async (req, res, next) => {
	const fetchingQuery = `
WITH
	AGG_HUMAN AS (
		SELECT
			REPORT_ID,
			SUM(DEATHS_COUNT) AS DEATHS,
			SUM(INJURED_COUNT) AS INJURIES,
			SUM(TOTAL_RESIDENTS_COUNT) AS RESIDENTS,
			SUM(PREGNANT_WOMEN_COUNT) AS PREGNANT_WOMENS,
			SUM(SCHOOL_GOING_CHILDREN_COUNT) AS SCHOOLD_GOING_KIDS,
			SUM(DISABLED_PERSONS_COUNT) AS DISABLED,
			SUM(MARRIED_COUPLES_COUNT) AS MARRIED_COUPLES
		FROM
			HUMAN_IMPACTS
		GROUP BY
			REPORT_ID
	),
	AGG_ANIMAL AS (
		SELECT
			REPORT_ID,
			SUM(
				SMALL_ANIMALS_DEATH_COUNT + BIG_ANIMALS_DEATH_COUNT
			) AS A_DEATHS,
			SUM(
				SMALL_ANIMALS_INJURED_COUNT + BIG_ANIMALS_INJURED_COUNT
			) AS A_INJURIES,
			SUM(SMALL_ANIMALS_DEATH_COUNT) AS A_SMALL_TOTAL_DEATHS,
			SUM(SMALL_ANIMALS_INJURED_COUNT) AS A_SMALL_TOTAL_INJURIES,
			SUM(BIG_ANIMALS_INJURED_COUNT) AS A_BIG_TOTAL_INJURIES,
			SUM(BIG_ANIMALS_DEATH_COUNT) AS A_BIG_TOTAL_DEATHS
		FROM
			ANIMAL_IMPACTS
		GROUP BY
			REPORT_ID
	),
	AGG_PROPERTY AS (
		SELECT
			REPORT_ID,
			COUNT(*) FILTER (
				WHERE
					IMPACT_LEVEL = 'minor'
			) AS P_MINOR,
			COUNT(*) FILTER (
				WHERE
					IMPACT_LEVEL = 'major'
			) AS P_MAJOR,
			COUNT(*) FILTER (
				WHERE
					IMPACT_LEVEL = 'fully_destroyed'
			) AS P_FULLY,
			COUNT(*) AS P_TOTAL
		FROM
			PROPERTY_IMPACTS
		GROUP BY
			REPORT_ID
	),
	DISASTER_MAP AS (
		SELECT
			INITCAP(U.DISTRICT) AS DISTRICT_NAME,
			INITCAP(U.TEHSIL) AS TEHSIL_NAME,
			JSONB_OBJECT_AGG(D.DISASTER_TYPE, TYPE_COUNTS.C) AS DISASTER_JSON
		FROM
			(
				SELECT
					R.U_ID,
					R.D_ID,
					COUNT(*) AS C
				FROM
					REPORTS R
				GROUP BY
					R.U_ID,
					R.D_ID
			) TYPE_COUNTS
			JOIN USERS U ON TYPE_COUNTS.U_ID = U.USER_ID
			JOIN DISASTERS D ON TYPE_COUNTS.D_ID = D.D_ID
		GROUP BY
			1,
			2
	),
	PROPERTY_TYPE_AGG AS (
		SELECT
			INITCAP(U.DISTRICT) AS DISTRICT_NAME,
			INITCAP(U.TEHSIL) AS TEHSIL_NAME,
			JSONB_OBJECT_AGG(PROP_COUNTS.PROPERTY_TYPE, PROP_COUNTS.DETAILS) AS TYPE_BREAKDOWN
		FROM
			(
				SELECT
					R.U_ID,
					PI.PROPERTY_TYPE,
					JSONB_BUILD_OBJECT(
						'minor',
						COUNT(*) FILTER (
							WHERE
								PI.IMPACT_LEVEL = 'minor'
						),
						'major',
						COUNT(*) FILTER (
							WHERE
								PI.IMPACT_LEVEL = 'major'
						),
						'fully_destroyed',
						COUNT(*) FILTER (
							WHERE
								PI.IMPACT_LEVEL = 'fully_destroyed'
						),
						'total',
						COUNT(*)
					) AS DETAILS
				FROM
					PROPERTY_IMPACTS PI
					JOIN REPORTS R ON PI.REPORT_ID = R.REPORT_ID
				GROUP BY
					R.U_ID,
					PI.PROPERTY_TYPE
			) PROP_COUNTS
			JOIN USERS U ON PROP_COUNTS.U_ID = U.USER_ID
		GROUP BY
			U.DISTRICT,
			U.TEHSIL
	),
	TEHSIL_STATS AS (
		SELECT
			INITCAP(U.DISTRICT) AS DISTRICT_NAME,
			INITCAP(U.TEHSIL) AS TEHSIL_NAME,
			COUNT(R.REPORT_ID) AS TOTAL_REPORTS,
			DM.DISASTER_JSON,
			COALESCE(SUM(H.DEATHS), 0) AS HUMAN_DEATHS,
			COALESCE(SUM(H.INJURIES), 0) AS HUMAN_INJURIES,
			COALESCE(SUM(H.RESIDENTS), 0) AS RESIDENTS,
			COALESCE(SUM(H.PREGNANT_WOMENS), 0) AS T_PREGNANT,
			COALESCE(SUM(H.SCHOOLD_GOING_KIDS), 0) AS T_KIDS,
			COALESCE(SUM(H.DISABLED), 0) AS T_DISABLED,
			COALESCE(SUM(H.MARRIED_COUPLES), 0) AS T_MARRIED,
			-- Combined Animal Totals for District Calculation
			COALESCE(SUM(A.A_DEATHS), 0) AS T_ANIMAL_DEATHS,
			COALESCE(SUM(A.A_INJURIES), 0) AS T_ANIMAL_INJURIES,
			-- Granular Animal Totals
			COALESCE(SUM(A.A_SMALL_TOTAL_DEATHS), 0) AS SMALL_DEATHS,
			COALESCE(SUM(A.A_SMALL_TOTAL_INJURIES), 0) AS SMALL_INJURIES,
			COALESCE(SUM(A.A_BIG_TOTAL_DEATHS), 0) AS BIG_DEATHS,
			COALESCE(SUM(A.A_BIG_TOTAL_INJURIES), 0) AS BIG_INJURIES,
			COALESCE(SUM(P.P_TOTAL), 0) AS PROP_TOTAL,
			COALESCE(SUM(P.P_MINOR), 0) AS PROP_MINOR,
			COALESCE(SUM(P.P_MAJOR), 0) AS PROP_MAJOR,
			COALESCE(SUM(P.P_FULLY), 0) AS PROP_FULLY,
			(
				(COALESCE(SUM(H.DEATHS), 0) * 10) + (COALESCE(SUM(P.P_FULLY), 0) * 5) + (COALESCE(SUM(H.INJURIES), 0) * 3) + (COUNT(R.REPORT_ID) * 1)
			) AS WEIGHTED_SCORE
		FROM
			REPORTS R
			INNER JOIN USERS U ON R.U_ID = U.USER_ID
			LEFT JOIN AGG_HUMAN H ON R.REPORT_ID = H.REPORT_ID
			LEFT JOIN AGG_ANIMAL A ON R.REPORT_ID = A.REPORT_ID
			LEFT JOIN AGG_PROPERTY P ON R.REPORT_ID = P.REPORT_ID
			LEFT JOIN DISASTER_MAP DM ON INITCAP(U.DISTRICT) = DM.DISTRICT_NAME
			AND INITCAP(U.TEHSIL) = DM.TEHSIL_NAME
		GROUP BY
			1,
			2,
			DM.DISASTER_JSON
	),
	DISTRICT_AGG AS (
		SELECT
			TS.DISTRICT_NAME,
			SUM(TS.TOTAL_REPORTS) AS D_REPORTS,
			SUM(TS.HUMAN_DEATHS) AS D_DEATHS,
			SUM(TS.HUMAN_INJURIES) AS D_INJURIES,
			SUM(TS.RESIDENTS) AS D_RESIDENTS,
			SUM(TS.T_PREGNANT) AS D_PREGNANT,
			SUM(TS.T_KIDS) AS D_KIDS,
			SUM(TS.T_DISABLED) AS D_DISABLED,
			SUM(TS.T_MARRIED) AS D_MARRIED,
			SUM(TS.T_ANIMAL_DEATHS) AS D_ANIMAL_DEATHS,
			SUM(TS.SMALL_DEATHS) AS D_SMALL_DEATHS,
			SUM(TS.SMALL_INJURIES) AS D_TOTAL_SMALL_INJURIES,
			SUM(TS.T_ANIMAL_INJURIES) AS D_ANIMAL_INJURIES,
			SUM(TS.SMALL_DEATHS) AS D_TOTAL_SMALL_DEATHS,
			SUM(TS.BIG_DEATHS) AS D_TOTAL_BIG_DEATHS,
			SUM(TS.BIG_INJURIES) AS D_TOTAL_BIG_INJURED,
			SUM(TS.PROP_TOTAL) AS D_PROP_TOTAL,
			SUM(TS.PROP_FULLY) AS D_PROP_FULLY,
			SUM(TS.PROP_MAJOR) AS D_PROP_MAJOR,
			SUM(TS.PROP_MINOR) AS D_PROP_MINOR,
			SUM(TS.WEIGHTED_SCORE) AS D_IMPACT,
			(
				SELECT
					JSONB_OBJECT_AGG(KEY, SUM_VAL)
				FROM
					(
						SELECT
							KEY,
							SUM(VALUE::INT) AS SUM_VAL
						FROM
							TEHSIL_STATS TS2,
							JSONB_EACH_TEXT(TS2.DISASTER_JSON)
						WHERE
							TS2.DISTRICT_NAME = TS.DISTRICT_NAME
						GROUP BY
							1
					) SUB
			) AS DISTRICT_DISASTER_COUNTS,
			JSONB_AGG(
				JSONB_BUILD_OBJECT(
					'tehsil_name',
					TS.TEHSIL_NAME,
					'total_reports',
					TS.TOTAL_REPORTS,
					'weighted_score',
					TS.WEIGHTED_SCORE,
					'disaster_mix',
					TS.DISASTER_JSON,
					'human_impacts',
					JSONB_BUILD_OBJECT(
						'deaths',
						TS.HUMAN_DEATHS,
						'pregnant',
						TS.T_PREGNANT,
						'disabled',
						TS.T_DISABLED,
						'kids',
						TS.T_KIDS,
						'married',
						TS.T_MARRIED,
						'injured',
						TS.HUMAN_INJURIES,
						'residents',
						TS.RESIDENTS
					),
					'animal_impacts',
					JSONB_BUILD_OBJECT(
						'deaths_total',
						TS.T_ANIMAL_DEATHS,
						'injuries_total',
						TS.T_ANIMAL_INJURIES,
						'deaths_big',
						TS.BIG_DEATHS,
						'deaths_small',
						TS.SMALL_DEATHS,
						'injuries_big',
						TS.BIG_INJURIES,
						'injuries_small',
						TS.SMALL_INJURIES
					),
					'property_summary',
					JSONB_BUILD_OBJECT(
						'fully_destroyed',
						TS.PROP_FULLY,
						'by_type',
						PTA.TYPE_BREAKDOWN
					)
				)
				ORDER BY
					TS.WEIGHTED_SCORE DESC
			) AS TEHSIL_BREAKDOWN
		FROM
			TEHSIL_STATS TS
			LEFT JOIN PROPERTY_TYPE_AGG PTA ON TS.DISTRICT_NAME = PTA.DISTRICT_NAME
			AND TS.TEHSIL_NAME = PTA.TEHSIL_NAME
		GROUP BY
			TS.DISTRICT_NAME
	)
SELECT
	SUM(D_REPORTS) OVER () AS GLOBAL_TOTAL_REPORTS,
	SUM(D_DEATHS) OVER () AS GLOBAL_TOTAL_DEATHS,
	SUM(D_INJURIES) OVER () AS GLOBAL_TOTAL_INJURIES,
	SUM(D_RESIDENTS) OVER () AS GLOBAL_TOTAL_RESIDENTS,
	SUM(D_PREGNANT) OVER () AS GLOBAL_TOTAL_PREGNANT,
	SUM(D_KIDS) OVER () AS GLOBAL_TOTAL_SCHOOL_GOING_CHILDREN,
	SUM(D_DISABLED) OVER () AS GLOBAL_TOTAL_DISABLED,
	SUM(D_MARRIED) OVER () AS GLOBAL_TOTAL_MARRIED_COUPLES,
	SUM(D_ANIMAL_DEATHS) OVER () AS GLOBAL_TOTAL_ANIMAL_DEATHS,
	SUM(D_SMALL_DEATHS) OVER() AS GLOBAL_TOTAL_SMALL_ANIMALS_DEATHS,
	SUM(D_TOTAL_SMALL_INJURIES) OVER() AS GLOBAL_TOTAL_SMALL_ANIMALS_INJURIES,
	SUM(D_TOTAL_BIG_DEATHS) OVER() AS GLOBAL_TOTAL_BIG_ANIMALS_DEATHS,
	SUM(D_TOTAL_BIG_INJURED) OVER() AS GLOBAL_TOTAL_BIG_ANIMALS_INJURIES,
	SUM(D_ANIMAL_INJURIES) OVER () AS GLOBAL_TOTAL_ANIMAL_INJURIES,
	SUM(D_PROP_TOTAL) OVER () AS GLOBAL_TOTAL_PROPERTIES,
	SUM(D_PROP_FULLY) OVER () AS GLOBAL_TOTAL_PROPERTIES_DESTROYED,
	SUM(D_PROP_MAJOR) OVER () AS GLOBAL_TOTAL_MAJOR_PROPERTIES,
	SUM(D_PROP_MINOR) OVER () AS GLOBAL_TOTAL_MINOR_PROPERTIES,
	DISTRICT_NAME,
	D_REPORTS AS DISTRICT_TOTAL_REPORTS,
	D_IMPACT AS DISTRICT_WEIGHTED_IMPACT,
	(
		SELECT
			JSONB_OBJECT_AGG(
				KEY,
				ROUND((VALUE::NUMERIC * 100.0) / D_REPORTS, 1)
			)
		FROM
			JSONB_EACH_TEXT(DISTRICT_DISASTER_COUNTS)
	) AS DISASTER_DISTRIBUTION_PCT,
	D_DEATHS AS DISTRICT_TOTAL_DEATHS,
	D_INJURIES AS DISTRICT_TOTAL_INJURIES,
	D_RESIDENTS AS DISTRICT_TOTAL_RESIDENTS,
	D_PREGNANT AS DISTRICT_TOTAL_PREGNANT,
	D_KIDS AS DISTRICT_TOTAL_SCHOOL_GOING_CHILDREN,
	D_DISABLED AS DISTRICT_TOTAL_DISABLED,
	D_MARRIED AS DISTRICT_TOTAL_MARRIED_COUPLES,
	D_ANIMAL_DEATHS AS DISTRICT_TOTAL_ANIMAL_DEATHS,
	D_ANIMAL_INJURIES AS DISTRICT_TOTAL_ANIMAL_INJURIES,
	D_TOTAL_SMALL_DEATHS AS DISTRICT_TOTAL_SMALL_ANIMALS_DEATHS,
	D_TOTAL_SMALL_INJURIES AS DISTRICT_TOTAL_SMALL_ANIMALS_INJURIES,
	D_TOTAL_BIG_DEATHS AS DISTRICT_TOTAL_BIG_ANIMALS_DEATHS,
	D_TOTAL_BIG_INJURED AS DISTRICT_TOTAL_BIG_ANIMALS_INJURIES,
	D_PROP_TOTAL AS DISTRICT_TOTAL_PROPERTIES,
	D_PROP_MINOR AS DISTRICT_PROPERTIES_MINOR_DAMAGE,
	D_PROP_MAJOR AS DISTRICT_PROPERTIES_MAJOR_DAMAGE,
	D_PROP_FULLY AS DISTRICT_PROPERTIES_FULLY_DESTROYED,
	TEHSIL_BREAKDOWN
FROM
	DISTRICT_AGG
ORDER BY
	D_IMPACT DESC;

`
	try {
		const response = await query(fetchingQuery, [])
		res.status(200).json(response.rows)
	} catch (error) {
		return next(errorGenerator('Something went wrong while fetching analytics', 500))
	}
}
module.exports = { fetchAdminAnalytics };